version: '3.8'

services:
  database:
    container_name: database
    image: mariadb/server:10.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'your-secret-root-password'
      MYSQL_DATABASE: 'your-project-database-name'
      MYSQL_USER: 'your-database-user-name'
      MYSQL_PASSWORD: 'your-secret-user-password'
    volumes:
      - ~/docker/volumes/mysql:/var/lib/mysql
    ports:
      - '4306:3306'
    networks:
      - default
  php:
    container_name: php
    build:
      context: ./docker/image/php
    volumes:
      - ./:/var/www/project
    ports:
      - '9000:9000'
    depends_on:
      - database
    networks:
      - default

  web:
    container_name: web
    image: nginx/stable-alpine
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d/default.conf
      - ./:/var/www/project
    ports:
      - '8080:80'
    depends_on:
      - database
      - php
    networks:
      - default
      - fe_net

networks:
  frontend:
    name: fe_net
    driver: bridge
  default:
    name: backend
